name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.14.2'
        host: 'linux'
        target: 'desktop'
        arch: ''
        dir: '${{ github.workspace }}/'
        install-deps: 'true'
        modules: 'qtcharts qtwebengine'
        mirror: 'http://mirrors.ocf.berkeley.edu/qt/'
        cached: 'false'
        aqtversion: '==0.9.4'
        py7zrversion: '==0.9.1'
        extra: '--external 7z'
    - name: install Boost
      run: wget https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0.tar.gz
           tar -xvf boost_1_74_0.tar.gz
           cd boost_1_74_0/
           ./bootstrap.sh
           ./b2 headers
    - name: build Anwalic
      run: ./test/1_buildAnwalic_forGithubActions.sh
    - name: build Test
      run: ./test/2_buildTest.sh
    - name: build Dependencies
      run: ./test/3_deploy.sh
    - name: run Test
      run: ./test/4_runTest.sh
